server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://database:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topic: users.events

eureka:
  instance:
    prefer-ip-address: false
    hostname: user-service
